sonar.organization=cdasse
sonar.projectKey=ecolocoach
sonar.projectName=EcoloCoach

sonar.exclusions=vendor/**, tests/**, src/DataFixtures/**, .github/**, run-tests.sh, README.md

sonar.sourceEncoding=UTF-8
