<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520095058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC1FA8BB03A8386 ON event_page (created_by_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8B896DBBDE ON event_page (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8BC76F1F52 ON event_page (deleted_by_id)');
        $this->addSql('CREATE TABLE event_page_event (event_page_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (event_page_id, event_id))');
        $this->addSql('CREATE INDEX IDX_5C12C5E8911CA4B ON event_page_event (event_page_id)');
        $this->addSql('CREATE INDEX IDX_5C12C5E71F7E88B ON event_page_event (event_id)');
        $this->addSql('CREATE TABLE event_part_event_page (event_part_id INT NOT NULL, event_page_id INT NOT NULL, PRIMARY KEY (event_part_id, event_page_id))');
        $this->addSql('CREATE INDEX IDX_F7671B7FC9B4E243 ON event_part_event_page (event_part_id)');
        $this->addSql('CREATE INDEX IDX_F7671B7F8911CA4B ON event_part_event_page (event_page_id)');
        $this->addSql('CREATE TABLE xpath_level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number_level INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, path_id_id INT NOT NULL, level_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A3640EE18A263689 ON xpath_level (path_id_id)');
        $this->addSql('CREATE INDEX IDX_A3640EE1159D9B5E ON xpath_level (level_id_id)');
        $this->addSql('CREATE INDEX IDX_A3640EE1B03A8386 ON xpath_level (created_by_id)');
        $this->addSql('CREATE INDEX IDX_A3640EE1896DBBDE ON xpath_level (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_A3640EE1C76F1F52 ON xpath_level (deleted_by_id)');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8BB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8BC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT FK_5C12C5E8911CA4B FOREIGN KEY (event_page_id) REFERENCES event_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT FK_5C12C5E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_part_event_page ADD CONSTRAINT FK_F7671B7FC9B4E243 FOREIGN KEY (event_part_id) REFERENCES event_part (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_part_event_page ADD CONSTRAINT FK_F7671B7F8911CA4B FOREIGN KEY (event_page_id) REFERENCES event_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE18A263689 FOREIGN KEY (path_id_id) REFERENCES path (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE1159D9B5E FOREIGN KEY (level_id_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE1B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE1C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_pages DROP CONSTRAINT fk_616f5459c76f1f52');
        $this->addSql('ALTER TABLE event_pages DROP CONSTRAINT fk_616f5459b03a8386');
        $this->addSql('ALTER TABLE event_pages DROP CONSTRAINT fk_616f5459896dbbde');
        $this->addSql('ALTER TABLE event_pages_event DROP CONSTRAINT fk_7dd4904d6f634f7');
        $this->addSql('ALTER TABLE event_pages_event DROP CONSTRAINT fk_7dd4904d71f7e88b');
        $this->addSql('ALTER TABLE event_part_event_pages DROP CONSTRAINT fk_db43c4bd6f634f7');
        $this->addSql('ALTER TABLE event_part_event_pages DROP CONSTRAINT fk_db43c4bdc9b4e243');
        $this->addSql('DROP TABLE event_pages');
        $this->addSql('DROP TABLE event_pages_event');
        $this->addSql('DROP TABLE event_part_event_pages');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_pages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_616f5459b03a8386 ON event_pages (created_by_id)');
        $this->addSql('CREATE INDEX idx_616f5459896dbbde ON event_pages (updated_by_id)');
        $this->addSql('CREATE INDEX idx_616f5459c76f1f52 ON event_pages (deleted_by_id)');
        $this->addSql('CREATE TABLE event_pages_event (event_pages_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (event_pages_id, event_id))');
        $this->addSql('CREATE INDEX idx_7dd4904d6f634f7 ON event_pages_event (event_pages_id)');
        $this->addSql('CREATE INDEX idx_7dd4904d71f7e88b ON event_pages_event (event_id)');
        $this->addSql('CREATE TABLE event_part_event_pages (event_part_id INT NOT NULL, event_pages_id INT NOT NULL, PRIMARY KEY (event_part_id, event_pages_id))');
        $this->addSql('CREATE INDEX idx_db43c4bdc9b4e243 ON event_part_event_pages (event_part_id)');
        $this->addSql('CREATE INDEX idx_db43c4bd6f634f7 ON event_part_event_pages (event_pages_id)');
        $this->addSql('ALTER TABLE event_pages ADD CONSTRAINT fk_616f5459c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_pages ADD CONSTRAINT fk_616f5459b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_pages ADD CONSTRAINT fk_616f5459896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_pages_event ADD CONSTRAINT fk_7dd4904d6f634f7 FOREIGN KEY (event_pages_id) REFERENCES event_pages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_pages_event ADD CONSTRAINT fk_7dd4904d71f7e88b FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part_event_pages ADD CONSTRAINT fk_db43c4bd6f634f7 FOREIGN KEY (event_pages_id) REFERENCES event_pages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part_event_pages ADD CONSTRAINT fk_db43c4bdc9b4e243 FOREIGN KEY (event_part_id) REFERENCES event_part (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8BB03A8386');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8B896DBBDE');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8BC76F1F52');
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT FK_5C12C5E8911CA4B');
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT FK_5C12C5E71F7E88B');
        $this->addSql('ALTER TABLE event_part_event_page DROP CONSTRAINT FK_F7671B7FC9B4E243');
        $this->addSql('ALTER TABLE event_part_event_page DROP CONSTRAINT FK_F7671B7F8911CA4B');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE18A263689');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE1159D9B5E');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE1B03A8386');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE1896DBBDE');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE1C76F1F52');
        $this->addSql('DROP TABLE event_page');
        $this->addSql('DROP TABLE event_page_event');
        $this->addSql('DROP TABLE event_part_event_page');
        $this->addSql('DROP TABLE xpath_level');
    }
}
