<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520095952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE follow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, follower_id INT NOT NULL, followed_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68344470AC24F853 ON follow (follower_id)');
        $this->addSql('CREATE INDEX IDX_68344470D956F010 ON follow (followed_id)');
        $this->addSql('CREATE INDEX IDX_68344470B03A8386 ON follow (created_by_id)');
        $this->addSql('CREATE INDEX IDX_68344470896DBBDE ON follow (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_68344470C76F1F52 ON follow (deleted_by_id)');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470AC24F853 FOREIGN KEY (follower_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470D956F010 FOREIGN KEY (followed_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT FK_68344470C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f27159d9b5e');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f273e5f2f7b');
        $this->addSql('DROP INDEX idx_63638f27159d9b5e');
        $this->addSql('DROP INDEX idx_63638f273e5f2f7b');
        $this->addSql('ALTER TABLE xlevel_event ADD level_id INT NOT NULL');
        $this->addSql('ALTER TABLE xlevel_event ADD event_id INT NOT NULL');
        $this->addSql('ALTER TABLE xlevel_event DROP level_id_id');
        $this->addSql('ALTER TABLE xlevel_event DROP event_id_id');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F275FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F2771F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_63638F275FB14BA7 ON xlevel_event (level_id)');
        $this->addSql('CREATE INDEX IDX_63638F2771F7E88B ON xlevel_event (event_id)');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee18a263689');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee1159d9b5e');
        $this->addSql('DROP INDEX idx_a3640ee1159d9b5e');
        $this->addSql('DROP INDEX idx_a3640ee18a263689');
        $this->addSql('ALTER TABLE xpath_level ADD path_id INT NOT NULL');
        $this->addSql('ALTER TABLE xpath_level ADD level_id INT NOT NULL');
        $this->addSql('ALTER TABLE xpath_level DROP path_id_id');
        $this->addSql('ALTER TABLE xpath_level DROP level_id_id');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE1D96C566B FOREIGN KEY (path_id) REFERENCES path (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT FK_A3640EE15FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_A3640EE1D96C566B ON xpath_level (path_id)');
        $this->addSql('CREATE INDEX IDX_A3640EE15FB14BA7 ON xpath_level (level_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470AC24F853');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470D956F010');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470B03A8386');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470896DBBDE');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT FK_68344470C76F1F52');
        $this->addSql('DROP TABLE follow');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F275FB14BA7');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F2771F7E88B');
        $this->addSql('DROP INDEX IDX_63638F275FB14BA7');
        $this->addSql('DROP INDEX IDX_63638F2771F7E88B');
        $this->addSql('ALTER TABLE xlevel_event ADD level_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE xlevel_event ADD event_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE xlevel_event DROP level_id');
        $this->addSql('ALTER TABLE xlevel_event DROP event_id');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f27159d9b5e FOREIGN KEY (level_id_id) REFERENCES level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f273e5f2f7b FOREIGN KEY (event_id_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_63638f27159d9b5e ON xlevel_event (level_id_id)');
        $this->addSql('CREATE INDEX idx_63638f273e5f2f7b ON xlevel_event (event_id_id)');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE1D96C566B');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT FK_A3640EE15FB14BA7');
        $this->addSql('DROP INDEX IDX_A3640EE1D96C566B');
        $this->addSql('DROP INDEX IDX_A3640EE15FB14BA7');
        $this->addSql('ALTER TABLE xpath_level ADD path_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE xpath_level ADD level_id_id INT NOT NULL');
        $this->addSql('ALTER TABLE xpath_level DROP path_id');
        $this->addSql('ALTER TABLE xpath_level DROP level_id');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee18a263689 FOREIGN KEY (path_id_id) REFERENCES path (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee1159d9b5e FOREIGN KEY (level_id_id) REFERENCES level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_a3640ee1159d9b5e ON xpath_level (level_id_id)');
        $this->addSql('CREATE INDEX idx_a3640ee18a263689 ON xpath_level (path_id_id)');
    }
}
