<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520085312 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84c896dbbde');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84c159d9b5e');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84cc76f1f52');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84cb03a8386');
        $this->addSql('DROP TABLE tip');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, level_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_4883b84cb03a8386 ON tip (created_by_id)');
        $this->addSql('CREATE INDEX idx_4883b84cc76f1f52 ON tip (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_4883b84c159d9b5e ON tip (level_id_id)');
        $this->addSql('CREATE INDEX idx_4883b84c896dbbde ON tip (updated_by_id)');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84c896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84c159d9b5e FOREIGN KEY (level_id_id) REFERENCES level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84cc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84cb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
