<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520085256 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_pages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event_pages_event (event_pages_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (event_pages_id, event_id))');
        $this->addSql('CREATE INDEX IDX_7DD4904D6F634F7 ON event_pages_event (event_pages_id)');
        $this->addSql('CREATE INDEX IDX_7DD4904D71F7E88B ON event_pages_event (event_id)');
        $this->addSql('ALTER TABLE event_pages_event ADD CONSTRAINT FK_7DD4904D6F634F7 FOREIGN KEY (event_pages_id) REFERENCES event_pages (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_pages_event ADD CONSTRAINT FK_7DD4904D71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_pages_event DROP CONSTRAINT FK_7DD4904D6F634F7');
        $this->addSql('ALTER TABLE event_pages_event DROP CONSTRAINT FK_7DD4904D71F7E88B');
        $this->addSql('DROP TABLE event_pages');
        $this->addSql('DROP TABLE event_pages_event');
    }
}
