<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520133348 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event_page_event (event_page_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (event_page_id, event_id))');
        $this->addSql('CREATE INDEX IDX_5C12C5E8911CA4B ON event_page_event (event_page_id)');
        $this->addSql('CREATE INDEX IDX_5C12C5E71F7E88B ON event_page_event (event_id)');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT FK_5C12C5E8911CA4B FOREIGN KEY (event_page_id) REFERENCES event_page (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT FK_5C12C5E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT FK_5C12C5E8911CA4B');
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT FK_5C12C5E71F7E88B');
        $this->addSql('DROP TABLE event_page');
        $this->addSql('DROP TABLE event_page_event');
    }
}
