<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520151807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, tip_id INT DEFAULT NULL, path_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9AEACC13476C47F6 ON level (tip_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13D96C566B ON level (path_id)');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13D96C566B FOREIGN KEY (path_id) REFERENCES path (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13476C47F6');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13D96C566B');
        $this->addSql('DROP TABLE level');
    }
}
