<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520093902 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_part (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_part_type VARCHAR(255) NOT NULL, picture_path VARCHAR(255) DEFAULT NULL, question VARCHAR(255) DEFAULT NULL, answers JSON DEFAULT \'[]\', right_answer VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, tag VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, sequence_number INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_56C43C6DB03A8386 ON event_part (created_by_id)');
        $this->addSql('CREATE INDEX IDX_56C43C6D896DBBDE ON event_part (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_56C43C6DC76F1F52 ON event_part (deleted_by_id)');
        $this->addSql('CREATE TABLE event_part_event_pages (event_part_id INT NOT NULL, event_pages_id INT NOT NULL, PRIMARY KEY (event_part_id, event_pages_id))');
        $this->addSql('CREATE INDEX IDX_DB43C4BDC9B4E243 ON event_part_event_pages (event_part_id)');
        $this->addSql('CREATE INDEX IDX_DB43C4BD6F634F7 ON event_part_event_pages (event_pages_id)');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6DC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_part_event_pages ADD CONSTRAINT FK_DB43C4BDC9B4E243 FOREIGN KEY (event_part_id) REFERENCES event_part (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_part_event_pages ADD CONSTRAINT FK_DB43C4BD6F634F7 FOREIGN KEY (event_pages_id) REFERENCES event_pages (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6DB03A8386');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6D896DBBDE');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6DC76F1F52');
        $this->addSql('ALTER TABLE event_part_event_pages DROP CONSTRAINT FK_DB43C4BDC9B4E243');
        $this->addSql('ALTER TABLE event_part_event_pages DROP CONSTRAINT FK_DB43C4BD6F634F7');
        $this->addSql('DROP TABLE event_part');
        $this->addSql('DROP TABLE event_part_event_pages');
    }
}
