<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520083318 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9AEACC13B03A8386 ON level (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13896DBBDE ON level (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13C76F1F52 ON level (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LEVEL_NAME ON level (name)');
        $this->addSql('CREATE TABLE path (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, nb_levels INT NOT NULL, description TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B548B0FB03A8386 ON path (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B548B0F896DBBDE ON path (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_B548B0FC76F1F52 ON path (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PATH_NAME ON path (name)');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, level_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4883B84C159D9B5E ON tip (level_id_id)');
        $this->addSql('CREATE INDEX IDX_4883B84CB03A8386 ON tip (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84C896DBBDE ON tip (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84CC76F1F52 ON tip (deleted_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, username VARCHAR(30) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, co2_impact DOUBLE PRECISION DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649539B0606 ON "user" (uid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0FC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C159D9B5E FOREIGN KEY (level_id_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13B03A8386');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13896DBBDE');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13C76F1F52');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0FB03A8386');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0F896DBBDE');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0FC76F1F52');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C159D9B5E');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CB03A8386');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C896DBBDE');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CC76F1F52');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE path');
        $this->addSql('DROP TABLE tip');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
