<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520132724 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conten TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE level ADD tip_id INT NOT NULL');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_9AEACC13476C47F6 ON level (tip_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE tip');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13476C47F6');
        $this->addSql('DROP INDEX IDX_9AEACC13476C47F6');
        $this->addSql('ALTER TABLE level DROP tip_id');
    }
}
