<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520144142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT fk_5c12c5e8911ca4b');
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT fk_5c12c5e71f7e88b');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT fk_9aeacc13476c47f6');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d649b03a8386');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d649896dbbde');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d649c76f1f52');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_page');
        $this->addSql('DROP TABLE event_page_event');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE path');
        $this->addSql('DROP TABLE tip');
        $this->addSql('DROP TABLE "user"');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE event_page_event (event_page_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (event_page_id, event_id))');
        $this->addSql('CREATE INDEX idx_5c12c5e71f7e88b ON event_page_event (event_id)');
        $this->addSql('CREATE INDEX idx_5c12c5e8911ca4b ON event_page_event (event_page_id)');
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, tip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9aeacc13476c47f6 ON level (tip_id)');
        $this->addSql('CREATE TABLE path (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, number_of_level INT NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conten TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_8d93d649896dbbde ON "user" (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d649539b0606 ON "user" (uid)');
        $this->addSql('CREATE INDEX idx_8d93d649b03a8386 ON "user" (created_by_id)');
        $this->addSql('CREATE INDEX idx_8d93d649c76f1f52 ON "user" (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT fk_5c12c5e8911ca4b FOREIGN KEY (event_page_id) REFERENCES event_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT fk_5c12c5e71f7e88b FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT fk_9aeacc13476c47f6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d649b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d649896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d649c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
