<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520104553 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE team_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_600C97B6B03A8386 ON team_challenge (created_by_id)');
        $this->addSql('CREATE INDEX IDX_600C97B6896DBBDE ON team_challenge (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_600C97B6C76F1F52 ON team_challenge (deleted_by_id)');
        $this->addSql('CREATE TABLE team_challenge_part (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, team_challenge_part_type VARCHAR(255) NOT NULL, picture_path VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, tag VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, sequence_number_part INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C7DDB6B7B03A8386 ON team_challenge_part (created_by_id)');
        $this->addSql('CREATE INDEX IDX_C7DDB6B7896DBBDE ON team_challenge_part (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_C7DDB6B7C76F1F52 ON team_challenge_part (deleted_by_id)');
        $this->addSql('CREATE TABLE team_challenge_part_team_challenge (team_challenge_part_id INT NOT NULL, team_challenge_id INT NOT NULL, PRIMARY KEY (team_challenge_part_id, team_challenge_id))');
        $this->addSql('CREATE INDEX IDX_BFC3372EECAD8A35 ON team_challenge_part_team_challenge (team_challenge_part_id)');
        $this->addSql('CREATE INDEX IDX_BFC3372E90241704 ON team_challenge_part_team_challenge (team_challenge_id)');
        $this->addSql('ALTER TABLE team_challenge ADD CONSTRAINT FK_600C97B6B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge ADD CONSTRAINT FK_600C97B6896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge ADD CONSTRAINT FK_600C97B6C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_part ADD CONSTRAINT FK_C7DDB6B7B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_part ADD CONSTRAINT FK_C7DDB6B7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_part ADD CONSTRAINT FK_C7DDB6B7C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge ADD CONSTRAINT FK_BFC3372EECAD8A35 FOREIGN KEY (team_challenge_part_id) REFERENCES team_challenge_part (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge ADD CONSTRAINT FK_BFC3372E90241704 FOREIGN KEY (team_challenge_id) REFERENCES team_challenge (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team_challenge DROP CONSTRAINT FK_600C97B6B03A8386');
        $this->addSql('ALTER TABLE team_challenge DROP CONSTRAINT FK_600C97B6896DBBDE');
        $this->addSql('ALTER TABLE team_challenge DROP CONSTRAINT FK_600C97B6C76F1F52');
        $this->addSql('ALTER TABLE team_challenge_part DROP CONSTRAINT FK_C7DDB6B7B03A8386');
        $this->addSql('ALTER TABLE team_challenge_part DROP CONSTRAINT FK_C7DDB6B7896DBBDE');
        $this->addSql('ALTER TABLE team_challenge_part DROP CONSTRAINT FK_C7DDB6B7C76F1F52');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge DROP CONSTRAINT FK_BFC3372EECAD8A35');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge DROP CONSTRAINT FK_BFC3372E90241704');
        $this->addSql('DROP TABLE team_challenge');
        $this->addSql('DROP TABLE team_challenge_part');
        $this->addSql('DROP TABLE team_challenge_part_team_challenge');
    }
}
