<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520152724 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT DEFAULT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, event_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC1FA8B539B0606 ON event_page (uid)');
        $this->addSql('CREATE INDEX IDX_BC1FA8B71F7E88B ON event_page (event_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8BB03A8386 ON event_page (created_by_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8B896DBBDE ON event_page (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8BC76F1F52 ON event_page (deleted_by_id)');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8B71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8BB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8BC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8B71F7E88B');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8BB03A8386');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8B896DBBDE');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8BC76F1F52');
        $this->addSql('DROP TABLE event_page');
    }
}
