<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520104841 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE team_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, team_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5ACE261296CD8AE ON team_log (team_id)');
        $this->addSql('CREATE INDEX IDX_D5ACE261B03A8386 ON team_log (created_by_id)');
        $this->addSql('CREATE INDEX IDX_D5ACE261896DBBDE ON team_log (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_D5ACE261C76F1F52 ON team_log (deleted_by_id)');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT FK_D5ACE261296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT FK_D5ACE261B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT FK_D5ACE261896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT FK_D5ACE261C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT FK_D5ACE261296CD8AE');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT FK_D5ACE261B03A8386');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT FK_D5ACE261896DBBDE');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT FK_D5ACE261C76F1F52');
        $this->addSql('DROP TABLE team_log');
    }
}
