<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520110820 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE team_challenge_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number_of_current INT NOT NULL, number_of_finished INT NOT NULL, number_of_quit INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, team_id INT NOT NULL, team_challenge_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DDAED6F7296CD8AE ON team_challenge_progress (team_id)');
        $this->addSql('CREATE INDEX IDX_DDAED6F790241704 ON team_challenge_progress (team_challenge_id)');
        $this->addSql('CREATE INDEX IDX_DDAED6F7B03A8386 ON team_challenge_progress (created_by_id)');
        $this->addSql('CREATE INDEX IDX_DDAED6F7896DBBDE ON team_challenge_progress (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_DDAED6F7C76F1F52 ON team_challenge_progress (deleted_by_id)');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT FK_DDAED6F7296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT FK_DDAED6F790241704 FOREIGN KEY (team_challenge_id) REFERENCES team_challenge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT FK_DDAED6F7B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT FK_DDAED6F7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT FK_DDAED6F7C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT FK_DDAED6F7296CD8AE');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT FK_DDAED6F790241704');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT FK_DDAED6F7B03A8386');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT FK_DDAED6F7896DBBDE');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT FK_DDAED6F7C76F1F52');
        $this->addSql('DROP TABLE team_challenge_progress');
    }
}
