<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520111201 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE xuser_team_challenge_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, membre_status VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, team_challenge_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_671EA7526C066AFE ON xuser_team_challenge_progress (target_user_id)');
        $this->addSql('CREATE INDEX IDX_671EA75290241704 ON xuser_team_challenge_progress (team_challenge_id)');
        $this->addSql('CREATE INDEX IDX_671EA752B03A8386 ON xuser_team_challenge_progress (created_by_id)');
        $this->addSql('CREATE INDEX IDX_671EA752896DBBDE ON xuser_team_challenge_progress (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_671EA752C76F1F52 ON xuser_team_challenge_progress (deleted_by_id)');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT FK_671EA7526C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT FK_671EA75290241704 FOREIGN KEY (team_challenge_id) REFERENCES team_challenge_progress (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT FK_671EA752B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT FK_671EA752896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT FK_671EA752C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT FK_671EA7526C066AFE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT FK_671EA75290241704');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT FK_671EA752B03A8386');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT FK_671EA752896DBBDE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT FK_671EA752C76F1F52');
        $this->addSql('DROP TABLE xuser_team_challenge_progress');
    }
}
