<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520131901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT fk_3bae0aa7c76f1f52');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT fk_3bae0aa7b03a8386');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT fk_3bae0aa7896dbbde');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT fk_bc1fa8bc76f1f52');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT fk_bc1fa8bb03a8386');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT fk_bc1fa8b896dbbde');
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT fk_5c12c5e8911ca4b');
        $this->addSql('ALTER TABLE event_page_event DROP CONSTRAINT fk_5c12c5e71f7e88b');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT fk_56c43c6d896dbbde');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT fk_56c43c6db03a8386');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT fk_56c43c6dc76f1f52');
        $this->addSql('ALTER TABLE event_part_event_page DROP CONSTRAINT fk_f7671b7fc9b4e243');
        $this->addSql('ALTER TABLE event_part_event_page DROP CONSTRAINT fk_f7671b7f8911ca4b');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT fk_68344470ac24f853');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT fk_68344470c76f1f52');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT fk_68344470896dbbde');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT fk_68344470b03a8386');
        $this->addSql('ALTER TABLE follow DROP CONSTRAINT fk_68344470d956f010');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT fk_9aeacc13896dbbde');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT fk_9aeacc13476c47f6');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT fk_9aeacc13b03a8386');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT fk_9aeacc13c76f1f52');
        $this->addSql('ALTER TABLE message_encouragement DROP CONSTRAINT fk_6b593c85c76f1f52');
        $this->addSql('ALTER TABLE message_encouragement DROP CONSTRAINT fk_6b593c85b03a8386');
        $this->addSql('ALTER TABLE message_encouragement DROP CONSTRAINT fk_6b593c85896dbbde');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT fk_b548b0fc76f1f52');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT fk_b548b0fb03a8386');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT fk_b548b0f896dbbde');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT fk_c4e0a61f896dbbde');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT fk_c4e0a61fb03a8386');
        $this->addSql('ALTER TABLE team DROP CONSTRAINT fk_c4e0a61fc76f1f52');
        $this->addSql('ALTER TABLE team_challenge DROP CONSTRAINT fk_600c97b6b03a8386');
        $this->addSql('ALTER TABLE team_challenge DROP CONSTRAINT fk_600c97b6c76f1f52');
        $this->addSql('ALTER TABLE team_challenge DROP CONSTRAINT fk_600c97b6896dbbde');
        $this->addSql('ALTER TABLE team_challenge_part DROP CONSTRAINT fk_c7ddb6b7c76f1f52');
        $this->addSql('ALTER TABLE team_challenge_part DROP CONSTRAINT fk_c7ddb6b7896dbbde');
        $this->addSql('ALTER TABLE team_challenge_part DROP CONSTRAINT fk_c7ddb6b7b03a8386');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge DROP CONSTRAINT fk_bfc3372e90241704');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge DROP CONSTRAINT fk_bfc3372eecad8a35');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT fk_ddaed6f7b03a8386');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT fk_ddaed6f7896dbbde');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT fk_ddaed6f7c76f1f52');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT fk_ddaed6f7296cd8ae');
        $this->addSql('ALTER TABLE team_challenge_progress DROP CONSTRAINT fk_ddaed6f790241704');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT fk_d5ace261896dbbde');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT fk_d5ace261296cd8ae');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT fk_d5ace261c76f1f52');
        $this->addSql('ALTER TABLE team_log DROP CONSTRAINT fk_d5ace261b03a8386');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84c896dbbde');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84cc76f1f52');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT fk_4883b84cb03a8386');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d649296cd8ae');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT fk_8d93d649d96c566b');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT fk_f68c4cfc76f1f52');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT fk_f68c4cf6c066afe');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT fk_f68c4cf71f7e88b');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT fk_f68c4cfb03a8386');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT fk_f68c4cf896dbbde');
        $this->addSql('ALTER TABLE user_level_progress DROP CONSTRAINT fk_c42d88cf6c066afe');
        $this->addSql('ALTER TABLE user_level_progress DROP CONSTRAINT fk_c42d88cf5fb14ba7');
        $this->addSql('ALTER TABLE user_level_progress DROP CONSTRAINT fk_c42d88cfb03a8386');
        $this->addSql('ALTER TABLE user_level_progress DROP CONSTRAINT fk_c42d88cf896dbbde');
        $this->addSql('ALTER TABLE user_level_progress DROP CONSTRAINT fk_c42d88cfc76f1f52');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f27b03a8386');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f275fb14ba7');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f27c76f1f52');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f27896dbbde');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT fk_63638f2771f7e88b');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee1c76f1f52');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee15fb14ba7');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee1d96c566b');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee1b03a8386');
        $this->addSql('ALTER TABLE xpath_level DROP CONSTRAINT fk_a3640ee1896dbbde');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT fk_671ea7526c066afe');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT fk_671ea752c76f1f52');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT fk_671ea75290241704');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT fk_671ea752896dbbde');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress DROP CONSTRAINT fk_671ea752b03a8386');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_page');
        $this->addSql('DROP TABLE event_page_event');
        $this->addSql('DROP TABLE event_part');
        $this->addSql('DROP TABLE event_part_event_page');
        $this->addSql('DROP TABLE follow');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE message_encouragement');
        $this->addSql('DROP TABLE path');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_challenge');
        $this->addSql('DROP TABLE team_challenge_part');
        $this->addSql('DROP TABLE team_challenge_part_team_challenge');
        $this->addSql('DROP TABLE team_challenge_progress');
        $this->addSql('DROP TABLE team_log');
        $this->addSql('DROP TABLE tip');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_event_progress');
        $this->addSql('DROP TABLE user_level_progress');
        $this->addSql('DROP TABLE xlevel_event');
        $this->addSql('DROP TABLE xpath_level');
        $this->addSql('DROP TABLE xuser_team_challenge_progress');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3bae0aa7c76f1f52 ON event (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_3bae0aa7b03a8386 ON event (created_by_id)');
        $this->addSql('CREATE INDEX idx_3bae0aa7896dbbde ON event (updated_by_id)');
        $this->addSql('CREATE TABLE event_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bc1fa8bb03a8386 ON event_page (created_by_id)');
        $this->addSql('CREATE INDEX idx_bc1fa8bc76f1f52 ON event_page (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_bc1fa8b896dbbde ON event_page (updated_by_id)');
        $this->addSql('CREATE TABLE event_page_event (event_page_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (event_page_id, event_id))');
        $this->addSql('CREATE INDEX idx_5c12c5e8911ca4b ON event_page_event (event_page_id)');
        $this->addSql('CREATE INDEX idx_5c12c5e71f7e88b ON event_page_event (event_id)');
        $this->addSql('CREATE TABLE event_part (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_part_type VARCHAR(255) NOT NULL, picture_path VARCHAR(255) DEFAULT NULL, question VARCHAR(255) DEFAULT NULL, answers JSON DEFAULT \'[]\', right_answer VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, tag VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, sequence_number INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_56c43c6dc76f1f52 ON event_part (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_56c43c6db03a8386 ON event_part (created_by_id)');
        $this->addSql('CREATE INDEX idx_56c43c6d896dbbde ON event_part (updated_by_id)');
        $this->addSql('CREATE TABLE event_part_event_page (event_part_id INT NOT NULL, event_page_id INT NOT NULL, PRIMARY KEY (event_part_id, event_page_id))');
        $this->addSql('CREATE INDEX idx_f7671b7fc9b4e243 ON event_part_event_page (event_part_id)');
        $this->addSql('CREATE INDEX idx_f7671b7f8911ca4b ON event_part_event_page (event_page_id)');
        $this->addSql('CREATE TABLE follow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, follower_id INT NOT NULL, followed_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_68344470c76f1f52 ON follow (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_68344470896dbbde ON follow (updated_by_id)');
        $this->addSql('CREATE INDEX idx_68344470b03a8386 ON follow (created_by_id)');
        $this->addSql('CREATE INDEX idx_68344470d956f010 ON follow (followed_id)');
        $this->addSql('CREATE INDEX idx_68344470ac24f853 ON follow (follower_id)');
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, tip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9aeacc13896dbbde ON level (updated_by_id)');
        $this->addSql('CREATE INDEX idx_9aeacc13476c47f6 ON level (tip_id)');
        $this->addSql('CREATE INDEX idx_9aeacc13b03a8386 ON level (created_by_id)');
        $this->addSql('CREATE INDEX idx_9aeacc13c76f1f52 ON level (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_level_name ON level (name)');
        $this->addSql('CREATE TABLE message_encouragement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6b593c85b03a8386 ON message_encouragement (created_by_id)');
        $this->addSql('CREATE INDEX idx_6b593c85896dbbde ON message_encouragement (updated_by_id)');
        $this->addSql('CREATE INDEX idx_6b593c85c76f1f52 ON message_encouragement (deleted_by_id)');
        $this->addSql('CREATE TABLE path (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, nb_levels INT NOT NULL, description TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b548b0f896dbbde ON path (updated_by_id)');
        $this->addSql('CREATE INDEX idx_b548b0fb03a8386 ON path (created_by_id)');
        $this->addSql('CREATE INDEX idx_b548b0fc76f1f52 ON path (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_path_name ON path (name)');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, total_co2_impact DOUBLE PRECISION DEFAULT \'0\' NOT NULL, membres_number INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_team_name ON team (name)');
        $this->addSql('CREATE INDEX idx_c4e0a61fb03a8386 ON team (created_by_id)');
        $this->addSql('CREATE INDEX idx_c4e0a61f896dbbde ON team (updated_by_id)');
        $this->addSql('CREATE INDEX idx_c4e0a61fc76f1f52 ON team (deleted_by_id)');
        $this->addSql('CREATE TABLE team_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_600c97b6c76f1f52 ON team_challenge (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_600c97b6b03a8386 ON team_challenge (created_by_id)');
        $this->addSql('CREATE INDEX idx_600c97b6896dbbde ON team_challenge (updated_by_id)');
        $this->addSql('CREATE TABLE team_challenge_part (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, team_challenge_part_type VARCHAR(255) NOT NULL, picture_path VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, tag VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, sequence_number_part INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c7ddb6b7b03a8386 ON team_challenge_part (created_by_id)');
        $this->addSql('CREATE INDEX idx_c7ddb6b7c76f1f52 ON team_challenge_part (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_c7ddb6b7896dbbde ON team_challenge_part (updated_by_id)');
        $this->addSql('CREATE TABLE team_challenge_part_team_challenge (team_challenge_part_id INT NOT NULL, team_challenge_id INT NOT NULL, PRIMARY KEY (team_challenge_part_id, team_challenge_id))');
        $this->addSql('CREATE INDEX idx_bfc3372e90241704 ON team_challenge_part_team_challenge (team_challenge_id)');
        $this->addSql('CREATE INDEX idx_bfc3372eecad8a35 ON team_challenge_part_team_challenge (team_challenge_part_id)');
        $this->addSql('CREATE TABLE team_challenge_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number_of_current INT NOT NULL, number_of_finished INT NOT NULL, number_of_quit INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, team_id INT NOT NULL, team_challenge_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ddaed6f790241704 ON team_challenge_progress (team_challenge_id)');
        $this->addSql('CREATE INDEX idx_ddaed6f7c76f1f52 ON team_challenge_progress (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_ddaed6f7896dbbde ON team_challenge_progress (updated_by_id)');
        $this->addSql('CREATE INDEX idx_ddaed6f7b03a8386 ON team_challenge_progress (created_by_id)');
        $this->addSql('CREATE INDEX idx_ddaed6f7296cd8ae ON team_challenge_progress (team_id)');
        $this->addSql('CREATE TABLE team_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, team_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d5ace261896dbbde ON team_log (updated_by_id)');
        $this->addSql('CREATE INDEX idx_d5ace261296cd8ae ON team_log (team_id)');
        $this->addSql('CREATE INDEX idx_d5ace261c76f1f52 ON team_log (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_d5ace261b03a8386 ON team_log (created_by_id)');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_4883b84cb03a8386 ON tip (created_by_id)');
        $this->addSql('CREATE INDEX idx_4883b84c896dbbde ON tip (updated_by_id)');
        $this->addSql('CREATE INDEX idx_4883b84cc76f1f52 ON tip (deleted_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, username VARCHAR(30) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, co2_impact DOUBLE PRECISION DEFAULT \'0\' NOT NULL, path_id INT DEFAULT NULL, team_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d649f85e0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
        $this->addSql('CREATE INDEX idx_8d93d649296cd8ae ON "user" (team_id)');
        $this->addSql('CREATE INDEX idx_8d93d649d96c566b ON "user" (path_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_8d93d649539b0606 ON "user" (uid)');
        $this->addSql('CREATE TABLE user_event_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, event_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f68c4cf6c066afe ON user_event_progress (target_user_id)');
        $this->addSql('CREATE INDEX idx_f68c4cf71f7e88b ON user_event_progress (event_id)');
        $this->addSql('CREATE INDEX idx_f68c4cfb03a8386 ON user_event_progress (created_by_id)');
        $this->addSql('CREATE INDEX idx_f68c4cf896dbbde ON user_event_progress (updated_by_id)');
        $this->addSql('CREATE INDEX idx_f68c4cfc76f1f52 ON user_event_progress (deleted_by_id)');
        $this->addSql('CREATE TABLE user_level_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, level_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_c42d88cf6c066afe ON user_level_progress (target_user_id)');
        $this->addSql('CREATE INDEX idx_c42d88cf5fb14ba7 ON user_level_progress (level_id)');
        $this->addSql('CREATE INDEX idx_c42d88cfb03a8386 ON user_level_progress (created_by_id)');
        $this->addSql('CREATE INDEX idx_c42d88cf896dbbde ON user_level_progress (updated_by_id)');
        $this->addSql('CREATE INDEX idx_c42d88cfc76f1f52 ON user_level_progress (deleted_by_id)');
        $this->addSql('CREATE TABLE xlevel_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(255) NOT NULL, sequence_number_event INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, level_id INT NOT NULL, event_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_63638f27c76f1f52 ON xlevel_event (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_63638f27896dbbde ON xlevel_event (updated_by_id)');
        $this->addSql('CREATE INDEX idx_63638f27b03a8386 ON xlevel_event (created_by_id)');
        $this->addSql('CREATE INDEX idx_63638f275fb14ba7 ON xlevel_event (level_id)');
        $this->addSql('CREATE INDEX idx_63638f2771f7e88b ON xlevel_event (event_id)');
        $this->addSql('CREATE TABLE xpath_level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number_level INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, path_id INT NOT NULL, level_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a3640ee1896dbbde ON xpath_level (updated_by_id)');
        $this->addSql('CREATE INDEX idx_a3640ee1b03a8386 ON xpath_level (created_by_id)');
        $this->addSql('CREATE INDEX idx_a3640ee15fb14ba7 ON xpath_level (level_id)');
        $this->addSql('CREATE INDEX idx_a3640ee1d96c566b ON xpath_level (path_id)');
        $this->addSql('CREATE INDEX idx_a3640ee1c76f1f52 ON xpath_level (deleted_by_id)');
        $this->addSql('CREATE TABLE xuser_team_challenge_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, membre_status VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, team_challenge_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_671ea7526c066afe ON xuser_team_challenge_progress (target_user_id)');
        $this->addSql('CREATE INDEX idx_671ea75290241704 ON xuser_team_challenge_progress (team_challenge_id)');
        $this->addSql('CREATE INDEX idx_671ea752b03a8386 ON xuser_team_challenge_progress (created_by_id)');
        $this->addSql('CREATE INDEX idx_671ea752896dbbde ON xuser_team_challenge_progress (updated_by_id)');
        $this->addSql('CREATE INDEX idx_671ea752c76f1f52 ON xuser_team_challenge_progress (deleted_by_id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT fk_3bae0aa7c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT fk_3bae0aa7b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT fk_3bae0aa7896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT fk_bc1fa8bc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT fk_bc1fa8bb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT fk_bc1fa8b896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT fk_5c12c5e8911ca4b FOREIGN KEY (event_page_id) REFERENCES event_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_page_event ADD CONSTRAINT fk_5c12c5e71f7e88b FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT fk_56c43c6d896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT fk_56c43c6db03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT fk_56c43c6dc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part_event_page ADD CONSTRAINT fk_f7671b7fc9b4e243 FOREIGN KEY (event_part_id) REFERENCES event_part (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_part_event_page ADD CONSTRAINT fk_f7671b7f8911ca4b FOREIGN KEY (event_page_id) REFERENCES event_page (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT fk_68344470ac24f853 FOREIGN KEY (follower_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT fk_68344470c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT fk_68344470896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT fk_68344470b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE follow ADD CONSTRAINT fk_68344470d956f010 FOREIGN KEY (followed_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT fk_9aeacc13896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT fk_9aeacc13476c47f6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT fk_9aeacc13b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT fk_9aeacc13c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_encouragement ADD CONSTRAINT fk_6b593c85c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_encouragement ADD CONSTRAINT fk_6b593c85b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_encouragement ADD CONSTRAINT fk_6b593c85896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT fk_b548b0fc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT fk_b548b0fb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT fk_b548b0f896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT fk_c4e0a61f896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT fk_c4e0a61fb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT fk_c4e0a61fc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge ADD CONSTRAINT fk_600c97b6b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge ADD CONSTRAINT fk_600c97b6c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge ADD CONSTRAINT fk_600c97b6896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_part ADD CONSTRAINT fk_c7ddb6b7c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_part ADD CONSTRAINT fk_c7ddb6b7896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_part ADD CONSTRAINT fk_c7ddb6b7b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge ADD CONSTRAINT fk_bfc3372e90241704 FOREIGN KEY (team_challenge_id) REFERENCES team_challenge (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_part_team_challenge ADD CONSTRAINT fk_bfc3372eecad8a35 FOREIGN KEY (team_challenge_part_id) REFERENCES team_challenge_part (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT fk_ddaed6f7b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT fk_ddaed6f7896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT fk_ddaed6f7c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT fk_ddaed6f7296cd8ae FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_challenge_progress ADD CONSTRAINT fk_ddaed6f790241704 FOREIGN KEY (team_challenge_id) REFERENCES team_challenge (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT fk_d5ace261896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT fk_d5ace261296cd8ae FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT fk_d5ace261c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE team_log ADD CONSTRAINT fk_d5ace261b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84c896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84cc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT fk_4883b84cb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d649296cd8ae FOREIGN KEY (team_id) REFERENCES team (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT fk_8d93d649d96c566b FOREIGN KEY (path_id) REFERENCES path (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT fk_f68c4cfc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT fk_f68c4cf6c066afe FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT fk_f68c4cf71f7e88b FOREIGN KEY (event_id) REFERENCES xlevel_event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT fk_f68c4cfb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT fk_f68c4cf896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_level_progress ADD CONSTRAINT fk_c42d88cf6c066afe FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_level_progress ADD CONSTRAINT fk_c42d88cf5fb14ba7 FOREIGN KEY (level_id) REFERENCES xpath_level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_level_progress ADD CONSTRAINT fk_c42d88cfb03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_level_progress ADD CONSTRAINT fk_c42d88cf896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_level_progress ADD CONSTRAINT fk_c42d88cfc76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f27b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f275fb14ba7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f27c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f27896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT fk_63638f2771f7e88b FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee1c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee15fb14ba7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee1d96c566b FOREIGN KEY (path_id) REFERENCES path (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee1b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xpath_level ADD CONSTRAINT fk_a3640ee1896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT fk_671ea7526c066afe FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT fk_671ea752c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT fk_671ea75290241704 FOREIGN KEY (team_challenge_id) REFERENCES team_challenge_progress (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT fk_671ea752896dbbde FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE xuser_team_challenge_progress ADD CONSTRAINT fk_671ea752b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
