<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520090001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4883B84CB03A8386 ON tip (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84C896DBBDE ON tip (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84CC76F1F52 ON tip (deleted_by_id)');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_pages ADD created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE event_pages ADD updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE event_pages ADD deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE event_pages ADD is_deleted BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE event_pages ADD created_by_id INT NOT NULL');
        $this->addSql('ALTER TABLE event_pages ADD updated_by_id INT NOT NULL');
        $this->addSql('ALTER TABLE event_pages ADD deleted_by_id INT NOT NULL');
        $this->addSql('ALTER TABLE event_pages ADD CONSTRAINT FK_616F5459B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_pages ADD CONSTRAINT FK_616F5459896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_pages ADD CONSTRAINT FK_616F5459C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_616F5459B03A8386 ON event_pages (created_by_id)');
        $this->addSql('CREATE INDEX IDX_616F5459896DBBDE ON event_pages (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_616F5459C76F1F52 ON event_pages (deleted_by_id)');
        $this->addSql('ALTER TABLE level ADD tip_id INT NOT NULL');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_9AEACC13476C47F6 ON level (tip_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CB03A8386');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C896DBBDE');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CC76F1F52');
        $this->addSql('DROP TABLE tip');
        $this->addSql('ALTER TABLE event_pages DROP CONSTRAINT FK_616F5459B03A8386');
        $this->addSql('ALTER TABLE event_pages DROP CONSTRAINT FK_616F5459896DBBDE');
        $this->addSql('ALTER TABLE event_pages DROP CONSTRAINT FK_616F5459C76F1F52');
        $this->addSql('DROP INDEX IDX_616F5459B03A8386');
        $this->addSql('DROP INDEX IDX_616F5459896DBBDE');
        $this->addSql('DROP INDEX IDX_616F5459C76F1F52');
        $this->addSql('ALTER TABLE event_pages DROP created_date');
        $this->addSql('ALTER TABLE event_pages DROP updated_date');
        $this->addSql('ALTER TABLE event_pages DROP deleted_date');
        $this->addSql('ALTER TABLE event_pages DROP is_deleted');
        $this->addSql('ALTER TABLE event_pages DROP created_by_id');
        $this->addSql('ALTER TABLE event_pages DROP updated_by_id');
        $this->addSql('ALTER TABLE event_pages DROP deleted_by_id');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13476C47F6');
        $this->addSql('DROP INDEX IDX_9AEACC13476C47F6');
        $this->addSql('ALTER TABLE level DROP tip_id');
    }
}
