<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520110436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_event_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, event_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F68C4CF6C066AFE ON user_event_progress (target_user_id)');
        $this->addSql('CREATE INDEX IDX_F68C4CF71F7E88B ON user_event_progress (event_id)');
        $this->addSql('CREATE INDEX IDX_F68C4CFB03A8386 ON user_event_progress (created_by_id)');
        $this->addSql('CREATE INDEX IDX_F68C4CF896DBBDE ON user_event_progress (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_F68C4CFC76F1F52 ON user_event_progress (deleted_by_id)');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT FK_F68C4CF6C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT FK_F68C4CF71F7E88B FOREIGN KEY (event_id) REFERENCES xlevel_event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT FK_F68C4CFB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT FK_F68C4CF896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_event_progress ADD CONSTRAINT FK_F68C4CFC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT FK_F68C4CF6C066AFE');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT FK_F68C4CF71F7E88B');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT FK_F68C4CFB03A8386');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT FK_F68C4CF896DBBDE');
        $this->addSql('ALTER TABLE user_event_progress DROP CONSTRAINT FK_F68C4CFC76F1F52');
        $this->addSql('DROP TABLE user_event_progress');
    }
}
