<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520151219 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE path (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, nb_of_levels INT NOT NULL, description TEXT NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B548B0F539B0606 ON path (uid)');
        $this->addSql('CREATE INDEX IDX_B548B0FB03A8386 ON path (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B548B0F896DBBDE ON path (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_B548B0FC76F1F52 ON path (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PATH_NAME ON path (name)');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0FC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0FB03A8386');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0F896DBBDE');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0FC76F1F52');
        $this->addSql('DROP TABLE path');
    }
}
