<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520095351 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE xlevel_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(255) NOT NULL, sequence_number_event INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, level_id_id INT NOT NULL, event_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63638F27159D9B5E ON xlevel_event (level_id_id)');
        $this->addSql('CREATE INDEX IDX_63638F273E5F2F7B ON xlevel_event (event_id_id)');
        $this->addSql('CREATE INDEX IDX_63638F27B03A8386 ON xlevel_event (created_by_id)');
        $this->addSql('CREATE INDEX IDX_63638F27896DBBDE ON xlevel_event (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_63638F27C76F1F52 ON xlevel_event (deleted_by_id)');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F27159D9B5E FOREIGN KEY (level_id_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F273E5F2F7B FOREIGN KEY (event_id_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F27B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F27896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xlevel_event ADD CONSTRAINT FK_63638F27C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F27159D9B5E');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F273E5F2F7B');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F27B03A8386');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F27896DBBDE');
        $this->addSql('ALTER TABLE xlevel_event DROP CONSTRAINT FK_63638F27C76F1F52');
        $this->addSql('DROP TABLE xlevel_event');
    }
}
