<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520151512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4883B84C539B0606 ON tip (uid)');
        $this->addSql('CREATE INDEX IDX_4883B84CB03A8386 ON tip (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84C896DBBDE ON tip (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84CC76F1F52 ON tip (deleted_by_id)');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CB03A8386');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C896DBBDE');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CC76F1F52');
        $this->addSql('DROP TABLE tip');
    }
}
