<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260603142151 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(255) NOT NULL, sequence_number INT DEFAULT NULL, co2_impact DOUBLE PRECISION DEFAULT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, level_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3BAE0AA7539B0606 ON event (uid)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA75FB14BA7 ON event (level_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7B03A8386 ON event (created_by_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7896DBBDE ON event (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7C76F1F52 ON event (deleted_by_id)');
        $this->addSql('CREATE TABLE event_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_number INT DEFAULT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, event_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC1FA8B539B0606 ON event_page (uid)');
        $this->addSql('CREATE INDEX IDX_BC1FA8B71F7E88B ON event_page (event_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8BB03A8386 ON event_page (created_by_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8B896DBBDE ON event_page (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_BC1FA8BC76F1F52 ON event_page (deleted_by_id)');
        $this->addSql('CREATE TABLE event_part (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_part_type VARCHAR(255) NOT NULL, picture_path VARCHAR(255) DEFAULT NULL, picture_alt VARCHAR(100) DEFAULT NULL, question VARCHAR(255) DEFAULT NULL, answers JSON DEFAULT NULL, right_answer VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, tag VARCHAR(30) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, sequence_number INT DEFAULT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, event_page_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_56C43C6D539B0606 ON event_part (uid)');
        $this->addSql('CREATE INDEX IDX_56C43C6D8911CA4B ON event_part (event_page_id)');
        $this->addSql('CREATE INDEX IDX_56C43C6DB03A8386 ON event_part (created_by_id)');
        $this->addSql('CREATE INDEX IDX_56C43C6D896DBBDE ON event_part (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_56C43C6DC76F1F52 ON event_part (deleted_by_id)');
        $this->addSql('CREATE TABLE level (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, sequence_number INT DEFAULT NULL, mascot1 VARCHAR(100) DEFAULT NULL, mascot2 VARCHAR(100) DEFAULT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, tip_id INT DEFAULT NULL, path_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9AEACC13539B0606 ON level (uid)');
        $this->addSql('CREATE INDEX IDX_9AEACC13476C47F6 ON level (tip_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13D96C566B ON level (path_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13B03A8386 ON level (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13896DBBDE ON level (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_9AEACC13C76F1F52 ON level (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LEVEL_NAME ON level (name)');
        $this->addSql('CREATE TABLE message_encouragement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B593C85539B0606 ON message_encouragement (uid)');
        $this->addSql('CREATE INDEX IDX_6B593C85B03A8386 ON message_encouragement (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6B593C85896DBBDE ON message_encouragement (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_6B593C85C76F1F52 ON message_encouragement (deleted_by_id)');
        $this->addSql('CREATE TABLE path (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, nb_of_levels INT NOT NULL, description TEXT NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B548B0F539B0606 ON path (uid)');
        $this->addSql('CREATE INDEX IDX_B548B0FB03A8386 ON path (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B548B0F896DBBDE ON path (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_B548B0FC76F1F52 ON path (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PATH_NAME ON path (name)');
        $this->addSql('CREATE TABLE tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4883B84C539B0606 ON tip (uid)');
        $this->addSql('CREATE INDEX IDX_4883B84CB03A8386 ON tip (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84C896DBBDE ON tip (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_4883B84CC76F1F52 ON tip (deleted_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(30) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, logo VARCHAR(255) NOT NULL, co2_impact DOUBLE PRECISION DEFAULT 0 NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, path_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649539B0606 ON "user" (uid)');
        $this->addSql('CREATE INDEX IDX_8D93D649D96C566B ON "user" (path_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649B03A8386 ON "user" (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649896DBBDE ON "user" (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649C76F1F52 ON "user" (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE xuser_level_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_status VARCHAR(255) NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, level_id INT NOT NULL, event_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F9CFD3E539B0606 ON xuser_level_event (uid)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E6C066AFE ON xuser_level_event (target_user_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E5FB14BA7 ON xuser_level_event (level_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E71F7E88B ON xuser_level_event (event_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3EB03A8386 ON xuser_level_event (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E896DBBDE ON xuser_level_event (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3EC76F1F52 ON xuser_level_event (deleted_by_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA75FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8B71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8BB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_page ADD CONSTRAINT FK_BC1FA8BC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6D8911CA4B FOREIGN KEY (event_page_id) REFERENCES event_page (id)');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6DB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_part ADD CONSTRAINT FK_56C43C6DC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13476C47F6 FOREIGN KEY (tip_id) REFERENCES tip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13D96C566B FOREIGN KEY (path_id) REFERENCES path (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE level ADD CONSTRAINT FK_9AEACC13C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_encouragement ADD CONSTRAINT FK_6B593C85B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_encouragement ADD CONSTRAINT FK_6B593C85896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_encouragement ADD CONSTRAINT FK_6B593C85C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0FB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0FC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tip ADD CONSTRAINT FK_4883B84CC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649D96C566B FOREIGN KEY (path_id) REFERENCES path (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E6C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3EC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA75FB14BA7');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7B03A8386');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7896DBBDE');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7C76F1F52');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8B71F7E88B');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8BB03A8386');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8B896DBBDE');
        $this->addSql('ALTER TABLE event_page DROP CONSTRAINT FK_BC1FA8BC76F1F52');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6D8911CA4B');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6DB03A8386');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6D896DBBDE');
        $this->addSql('ALTER TABLE event_part DROP CONSTRAINT FK_56C43C6DC76F1F52');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13476C47F6');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13D96C566B');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13B03A8386');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13896DBBDE');
        $this->addSql('ALTER TABLE level DROP CONSTRAINT FK_9AEACC13C76F1F52');
        $this->addSql('ALTER TABLE message_encouragement DROP CONSTRAINT FK_6B593C85B03A8386');
        $this->addSql('ALTER TABLE message_encouragement DROP CONSTRAINT FK_6B593C85896DBBDE');
        $this->addSql('ALTER TABLE message_encouragement DROP CONSTRAINT FK_6B593C85C76F1F52');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0FB03A8386');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0F896DBBDE');
        $this->addSql('ALTER TABLE path DROP CONSTRAINT FK_B548B0FC76F1F52');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CB03A8386');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84C896DBBDE');
        $this->addSql('ALTER TABLE tip DROP CONSTRAINT FK_4883B84CC76F1F52');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649D96C566B');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649B03A8386');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649896DBBDE');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649C76F1F52');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E6C066AFE');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E5FB14BA7');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E71F7E88B');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3EB03A8386');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E896DBBDE');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3EC76F1F52');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_page');
        $this->addSql('DROP TABLE event_part');
        $this->addSql('DROP TABLE level');
        $this->addSql('DROP TABLE message_encouragement');
        $this->addSql('DROP TABLE path');
        $this->addSql('DROP TABLE tip');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE xuser_level_event');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
