<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520153815 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE xuser_level_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_status VARCHAR(255) NOT NULL, uid UUID NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, target_user_id INT NOT NULL, level_id INT NOT NULL, event_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F9CFD3E539B0606 ON xuser_level_event (uid)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E6C066AFE ON xuser_level_event (target_user_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E5FB14BA7 ON xuser_level_event (level_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E71F7E88B ON xuser_level_event (event_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3EB03A8386 ON xuser_level_event (created_by_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3E896DBBDE ON xuser_level_event (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_5F9CFD3EC76F1F52 ON xuser_level_event (deleted_by_id)');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E6C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E5FB14BA7 FOREIGN KEY (level_id) REFERENCES level (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_level_event ADD CONSTRAINT FK_5F9CFD3EC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E6C066AFE');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E5FB14BA7');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E71F7E88B');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3EB03A8386');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3E896DBBDE');
        $this->addSql('ALTER TABLE xuser_level_event DROP CONSTRAINT FK_5F9CFD3EC76F1F52');
        $this->addSql('DROP TABLE xuser_level_event');
    }
}
