name: Deploy

on:
    workflow_run:
        workflows: [ "Build and Package" ]
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest

        steps:
            -   name: Deploy on Alwaysdata
                uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
                with:
                    host: "ssh-ecolocoach.alwaysdata.net"
                    username: "ecolocoach"
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: "echo 'Connexion demandée !'"
